### ISSUE TITLE
Spotify still not placed correctly

### ISSUE THREAD

**Issue by ItsLogic** [Slddev/ModernX-Theme#14]
Just saw the commits 632bd70 and 6b2b145 thought I should mention that its still broken (on my end at least) even after these fixes.

![image](https://user-images.githubusercontent.com/38233332/149496344-21d56717-7625-416c-875d-88de3ed1bffd.png)

I was able to fix the positioning myself (as long as I wasnt in a voice call) yesterday before these two commits using a pretty hacky fix by hardcoding the top margin. Im not too knowledgeable in css so im not sure if its possible to automatically calculate those values but if so it should mostly fix the alignment issue as long as its applied to the version before the two most recent commits.
![image](https://user-images.githubusercontent.com/38233332/149496887-86cb4daf-93da-47ad-9107-6a59e8b5f91d.png)

```css
.spotify-cover{
  margin-top:708px;
}
.spotify-title{
  margin-top:712px;
}
.spotify-buttons{
  margin-left:-8px;
}
```
