### ISSUE TITLE
[Feature] Solution suggestion for recurring spotify issue.

### ISSUE THREAD

**Issue by AleanaA** [Slddev/ModernX-Theme#20]
### Suggestion

Rather than just trying to cram the default UI into the bottom left, why not embrace the icon issue shown in a previous issue?

### Benefit

Overall, I feel like having an icon with a dropdown for the controls overall suits the design of the theme more, and seems like a more elegant, and probably less frustratingly inconsistent, solution.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

For full clarification, looking at #4 , I'm sure it's unintentional for the icon to show next to the user stuff, but it seems like that's a pretty fitting spot for it.
A general idea would be to have a similar design to the user dropdown, with an icon, and the title of the song to the right, and then a dropdown with the progress and controls, keeping the design of the spotify modal in line with the rest of the theme, rather than shoving it into the bottom right where even when aligned on a case by case basis feels really out of place.

Would just make a PR for this, but this kind of thing is way way outside my knowledge of css.

**Comment by Slddev** [comment]
Sadly I cannot add a dropdown to the icon. I will be fixing it soon though.

**Comment by AleanaA** [comment]
> Sadly I cannot add a dropdown to the icon. I will be fixing it soon though.

Noted
I put in some time to figuring things out, and ended up coming up with this nice concept, not confident enough in what I've done to PR it, but I can confirm that this resizes fine, and looks pretty clean. Built the idea off of a right based pop out made by [Gianology](https://canary.discord.com/channels/538759280057122817/755005803303403570/794666147928735754):


```css
.powercord-spotify {
  transition-property: left, height;
  transition-duration:  0.4s;
  border-top-right-radius: 25px;
  position: absolute;
  z-index: 1;
  bottom: -12px;
  left: -150px;
  width: 200px !important;
  height: 35px;
  background-color: var(--background-secondary);
  border-top: 1px solid var(--spotify-color);
  border-right: 1px solid var(--spotify-color);
  overflow: hidden;
}

.powercord-spotify:hover {
  left: 0px;
  height: 60px;
}

.powercord-spotify>.container-YkUktl>.avatarWrapper-1B9FTW {
  position: absolute;
  top: 10px;
  left: 155px;
  right: 10px;
  margin: 0 auto !important;
  transition: 0.2s
}
.powercord-spotify:hover>.container-YkUktl>.avatarWrapper-1B9FTW {
  position: absolute;
  top: 10px;
  left: 155px;
  right: 10px;
  margin: 0 auto !important;
  transition: 0.2s
}

.powercord-spotify>.container-YkUktl>.nameTag-sc-gpq {
  position: absolute;
  top: 4px;
  left: 4px;
  margin: 0 0 !important;
  transition: 0.2s;
  width: 70%;
}
  
.powercord-spotify:hover>.container-YkUktl>.nameTag-sc-gpq {
  top: 4px !important;
}

.spotify-buttons {
  position: absolute;
  top: 30px !important;
  left: 4px !important;
  margin: 0 0 !important;
  transition: 0.2s;
  width: 100%;
}
.spotify-extra-controls,
.powercord-spotify:hover .spotify-extra-controls {
  position: absolute;
  top: 62px !important;
  left: 70px !important;
  margin: 0 0 !important;
  transition: 0.2s;
  width: 100%;
  height: 0 !important;
  opacity: 1 !important;
}
.spotify-seek {
  display: none !important;
}
```

I'm pretty happy personally with the result, and although I hid the seek section, I'm sure that could be easily fit into the bottom quite snuggly:
![image](https://user-images.githubusercontent.com/8583835/154246148-c97a2303-e4a1-410d-95ee-b319585e3e09.png)
![image](https://user-images.githubusercontent.com/8583835/154246179-a6522429-00c2-4423-8740-50ea07b7806a.png)

Also screenshots for a resized to smallest discord, as resizing was a big problem:
![image](https://user-images.githubusercontent.com/8583835/154246858-a81c4bf2-32ea-450f-a8c9-964a069ac649.png)
![image](https://user-images.githubusercontent.com/8583835/154246885-985b5487-2832-42b8-9d24-719e751b2598.png)

Hope this helps out in fixing the issue!
